nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/ArimaSpecUI.java
Corrections following the comments of ISTAT
=> Correction and re-organisation of the AMI parameters of Tramo (GUI)

nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/ArimaSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/TransformSpecUI.java
using the given description for some specification parameter (ArimaSpecUI)
correcting misspelling (TransformSpecUI)
=> Enhancement

README.md, nbdemetra-benchmarking/src/main/java/ec/nbdemetra/benchmarking/descriptors/DentonSpecUI.java, nbdemetra-benchmarking/src/main/java/ec/nbdemetra/disaggregation/descriptors/AdvancedSpecUI.java, nbdemetra-benchmarking/src/main/java/ec/nbdemetra/disaggregation/descriptors/BasicSpecUI.java, nbdemetra-benchmarking/src/main/java/ec/nbdemetra/disaggregation/ui/TsDisaggregationViewFactory.java, nbdemetra-sa-ext/src/main/java/be/nbb/tramoseats/io/LegacyDecoder.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/chart3d/functions/ConfigurationToolBar.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/chart3d/functions/Functions2DChart.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/chart3d/functions/SurfacePlotterUI.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/chart3d/functions/SurfacePlotterView.java, nbdemetra-ui/src/main/java/ec/ui/view/tsprocessing/TsDocumentInformationExtractor.java
=> Temporal disaggregation (improvements)

nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/X11SpecUI.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyEditorRegistry.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyRendererFactory.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/SigmavecPropertyEditor.java
Dear all, 
please find enclosed the request to integrate the x11 specification Calendarsigma. 
Regards Christiane
=> Cochran app

nbdemetra-ui/src/main/java/ec/nbdemetra/ui/DemetraUI.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/calendars/actions/RemoveCalendarAction.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/chart3d/functions/SurfacePlotterView.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/DhmsPropertyEditor.java
I found the CompositCalender bug while testing, the other "fixes" are just three little things from findbugs.
=> Fixed bug: CompositCalender can now be removed from the workspace + minor fixes

nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/TramoSpecPropertyEditor.java, nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/ui/CheckLastBatchUI.java, nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/ui/JTsAnomalyGrid.java, nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/ui/JTsCheckLastList.java, nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/ui/OutliersTopComponent.java
=> Different changes/fixes in Anomaly Detection

nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/ArimaSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/BasicSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/CalendarSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/EasterSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/EstimateSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/OutlierSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/RegressionSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/SeatsSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/ArimaSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/BasicSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/CalendarSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/EasterSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/EstimateSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/OutlierSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/RegArimaSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/RegressionSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/TradingDaysSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/TransformSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/X11SpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/X13SpecUI.java
This is the first step to solve issue number #61 by creating externalisation of the messages to be used with the branding mechanism.
=> Localized string messages for SA-Descriptors.

nbdemetra-ui/src/main/java/ec/ui/list/JTsVariableList.java, nbdemetra-ui/src/test/java/ec/nbdemetra/ui/demo/impl/TsVariableListFactory.java, nbdemetra-ui/src/test/java/ec/nbdemetra/ui/demo/impl/TsVariableListHandler.java
=> Added display of regression variables.

nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/ui/TramoSeatsViewFactory.java, nbdemetra-ui/src/main/java/ec/ui/view/tsprocessing/sa/SaDocumentViewFactory.java
New panel in the graphical interface of Tramo-Seats. A similar solution should be used for X12 (currently, the result is mixed in the details of the quality measures of X11)
=> Stationary variance decomposition in Tramo-Seats

nbdemetra-ui/src/main/java/ec/ui/view/SlidingSpanView.java
=> Fixed scale in SlidingSpanView.

nbdemetra-ui/src/main/java/ec/nbdemetra/ui/calendars/EasterRelatedEventBean.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/calendars/NationalCalendarPanel.form, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/calendars/NationalCalendarPanel.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/calendars/actions/AddCalendarAction.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/calendars/actions/EditCalendarAction.java
New Julian Calendar option in NationalCalendarPanel
=> Julian Calendar option in creating/editing workspace calendar

nbdemetra-utils/src/main/java/ec/util/grid/swing/JGrid.java
=> Fix for graphic glitch when modifying content of a zoomed grid.

nbdemetra-ui/src/main/java/ec/ui/view/SIView.java
=> Fixed master/detail switch in SIRatio chart.

nbdemetra-ui/src/main/java/ec/ui/view/SIView.java
Available years are now correctly displayed for the selected period
(See issue #184)
=> SI-Ratio chart now correctly displays the available years

nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaBatchUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/SeatsSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/TradingDaysSpecUI.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyEditorRegistry.java, nbdemetra-ui/src/main/java/ec/ui/descriptors/TsPeriodSelectorUI.java, nbdemetra-ui/src/main/java/ec/ui/view/tsprocessing/DefaultProcessingViewer.java, nbdemetra-ui/src/main/java/ec/ui/view/tsprocessing/TsProcessingViewer.java
- Fixes behaviour of Apply/Restore/Save buttons in property sheets.
- Bug fix in CustomPropertyEditor registry
- SaBatchUI : Warning message when applied but unsaved changes in spec are left when changing selected item
=> Spec buttons fix

pom.xml
=> Updated dependencies to Java8.

nbdemetra-sa/src/main/java/ec/nbdemetra/sa/MultiProcessingDocument.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaBatchUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaItemChildFactory.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaItemComparer.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaItemNode.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaItemNotifier.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/actions/ChangeSpecification.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/actions/RenameSaItem.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/NbUtilities.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/nodes/StringProperty.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyRendererFactory.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ws/nodes/ItemWsNode.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ws/nodes/WsNode.java, nbdemetra-ui/src/main/java/ec/ui/list/JTsVariableList.java
Shouldn't build in Travis at the moment because it needs jdemetra/jdemetra-core#185
=> Meta data branch

nbdemetra-sa/src/main/java/ec/nbdemetra/x13/ui/X13ViewFactory.java
=> Add composite filters to the Final Filters output. Shouldn't build in Travis at the moment because it needs jdemetra/jdemetra-core#186

nbdemetra-businesscycle/src/main/java/ec/nbdemetra/businesscycle/descriptors/HodrickPrescottSpecUI.java, nbdemetra-ui/pom.xml, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/AutoCompletedPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/AutoCompletedPropertyEditor3.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/CharsetPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/ComboBoxPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/DataFormatPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/DayPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/FormattedPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/JSpinFieldPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/ListSelectionEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/NodePropertySetBuilder.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyEditorRegistry.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/DoublePropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/EnumPropertyEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/JDayPropertyEditor.java, nbdemetra-ui/src/main/java/internal/CustomPropertyEditorSupport.java, nbdemetra-ui/src/main/java/internal/JTextComponents.java, nbdemetra-ui/src/test/java/ec/nbdemetra/ui/demo/impl/L2fprodFactory.java, nbdemetra-ui/src/test/java/ec/nbdemetra/ui/demo/impl/PropertyEditorFactory.java
=> Fix some property editors

nbdemetra-ui/src/main/java/ec/ui/view/SIView.java
Allow users to select observations more easily.
Added a better looking tooltip and highlight of observations by pressing 'R' key.
Fixes #210 (SI-ratios)
=> Improved SI ratio chart

nbdemetra-ui/src/main/java/ec/nbdemetra/ui/chart3d/functions/SurfacePlotterView.java
Better feedback when the function provided to the 3D likelihood chart doesn't contain parameters
=> Likelihood 3D chart (without parameters)

nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/RegressionSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/RegressionSpecUI.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/Coefficients.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CoefficientsEditorDialog.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyEditorRegistry.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/CustomPropertyRendererFactory.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/FixedCoefficientsEditor.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/PropertiesPanelFactory.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/RampsEditor.java
- Added editors to be able to edit/add/delete the coefficients
- Registering the custom property editor/renderer
=> Fixed regression coefficients

nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/ui/CheckLastBatchUI.java, nbdemetra-anomalydetection/src/main/java/ec/nbdemetra/anomalydetection/ui/JTsCheckLastList.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/MatrixView.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaBatchUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/sa/actions/CopyComponents.java
- User can export results from the Check Last view to the clipboard (Fixes #263)
- Bug fix in Copy Components action
- Custom diagnostics matrix view in SA processing view
=> Check Last copy + Custom diagnostics matrix

nbdemetra-utils/src/main/java/ec/util/desktop/impl/Util.java, nbdemetra-utils/src/main/java/ec/util/desktop/impl/XdgDesktop.java, nbdemetra-utils/src/test/java/ec/util/desktop/impl/XdgDesktopTest.java
=> Fixed NPE when xdg config file is missing.

nbdemetra-ui/src/main/java/ec/nbdemetra/ws/FileRepository.java
=> Fixed deletion of workspace items.

nbdemetra-sa/src/main/java/ec/nbdemetra/sa/DiagnosticsMatrixView.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/descriptors/RegressionSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/tramoseats/ui/TramoSeatsViewFactory.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/RegressionSpecUI.java, nbdemetra-sa/src/main/java/ec/nbdemetra/x13/ui/X13ViewFactory.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/variables/actions/ImportVariablesAction.java
matrix panel, importation of external variables, fixed coefficients disabled when the transformation is not specified
=> Small bugs in RC1

nbdemetra-sa/src/main/java/ec/nbdemetra/sa/SaBatchUI.java
=> Fixed column glitch in SaBatchUI when refreshing table.

nbdemetra-sa/src/main/java/ec/nbdemetra/sa/DiagnosticsMatrixView.java
if not no outliers found or if no calendars are significant.
=> Diagnostics matrix view precise the no data message

nbdemetra-ui/src/main/java/ec/nbdemetra/ui/Installer.java, nbdemetra-ui/src/main/java/ec/ui/view/AChartView.java, nbdemetra-ui/src/main/java/ec/ui/view/ARPView.java, nbdemetra-ui/src/main/java/ec/ui/view/AcgfView.java, nbdemetra-ui/src/main/java/ec/ui/view/AutoCorrelationsView.java, nbdemetra-ui/src/main/java/ec/ui/view/DistributionView.java, nbdemetra-ui/src/main/java/ec/ui/view/JChartPanel.java, nbdemetra-ui/src/main/java/ec/ui/view/MarginView.java, nbdemetra-ui/src/main/java/ec/ui/view/SlidingSpanView.java, nbdemetra-ui/src/main/java/ec/ui/view/SpectrumView.java, nbdemetra-ui/src/main/java/ec/ui/view/res/ResidualsView.java, nbdemetra-utils/src/main/java/ec/util/chart/swing/Charts.java, nbdemetra-utils/src/main/java/ec/util/chart/swing/JTimeSeriesChart.java, nbdemetra-utils/src/main/java/ec/util/chart/swing/SparklineCellRenderer.java, nbdemetra-utils/src/test/java/ec/util/chart/swing/JTimeSeriesRendererSupportDemo.java
=> Fix chart rendering with Java9/10.

nbdemetra-sa/src/main/java/ec/nbdemetra/sa/actions/LocalRefreshParameters.java
=> Fixed default value in local refresh of arima parameters.

nbdemetra-sa/src/main/java/ec/nbdemetra/x13/descriptors/X11SpecUI.java, nbdemetra-ui/src/main/java/ec/nbdemetra/ui/properties/l2fprod/OutlierDefinitionsEditor.java
Add seasonal adjustment for half yearly data with X13. Then automatic detection of henderson uses always lenght=5.
=> Half yearly with X13 

nbdemetra-app/pom.xml, nbdemetra-ui/pom.xml, pom.xml
=> Fix JavaHelp missing menu and shortcut

demetra-desktop-api/src/main/java/demetra/desktop/components/tools/JStabilityView.java, demetra-desktop-api/src/main/java/demetra/desktop/workspace/ui/WorkspaceTopComponent.java, demetra-desktop-api/src/main/java/demetra/desktop/workspace/ui/WorkspaceTsTopComponent.java, demetra-desktop-app/pom.xml, demetra-desktop-sa/demetra-desktop-sa-ui/src/main/java/demetra/desktop/sa/output/Matrix.java
=> Removal of STL
